### Регистрация
POST http://localhost:3000/signup
Content-Type: application/json

{

    "username": "exampleuser11",
    "about": "exampleuser9",
    "avatar": "https://i.pravatar.cc/150?img=3",
    "email": "user10@yandex.ru",
    "password": "somestrongpassword11"

}

### Авторизация
POST http://127.0.0.1:3000/signin
Content-Type: application/json

{
    "username": "exampleuser8",
    "password": "somestrongpassword8"
}

# {
#     "email": "admin@admin.admin",
#     "password": "admin"
# }

###

# Васёк
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEyLCJpYXQiOjE2NzEyMTU5NDUsImV4cCI6MTY3MzgwNzk0NX0.SB0Kx4O-W4BSITZOETfVjLavXP2ODMTK3HZMISR5gNU
# @token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjI4LCJpYXQiOjE2NzEyNzQ5NDAsImV4cCI6MTY3Mzg2Njk0MH0.dL7_J14NzlwOXz_8YPh_dB-EYZmI8h9F6zdCA2MovIk


### endpoint /users/me
GET http://127.0.0.1:3000/users/me
Authorization: Bearer {{token}}

### endpoint /users/:username
GET http://127.0.0.1:3000/users/exampleuser5
Authorization: Bearer {{token}}

### endpoint /users/find
POST http://127.0.0.1:3000/users/find
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "query": "exampleuser56"
}

### endpoint /users/me
PATCH http://127.0.0.1:3000/users/me
Content-Type: application/json
Authorization: Bearer {{token}}

{

    "about": "exampleuser5",
    "username": "exampleuser5",
    "email": "user5@yandex.ru"

}

### endpoint /users/me/wishes
GET http://127.0.0.1:3000/users/me/wishes
Authorization: Bearer {{token}}

### endpoint /users/{username}/wishes
GET http://127.0.0.1:3000/users/exampleuser5/wishes
Authorization: Bearer {{token}}






### endpoint /wishes
POST http://127.0.0.1:3000/wishes
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Блендер Bosch погружной",
    "link": "https://www.onlinetrade.ru/catalogue/blendery-c75/bosch/blender_bosch_msm_66020_pogruzhnoy_msm66020-190188.html",
    "price": 2990,
    "image": "https://static.onlinetrade.ru/img/items/b/blender_bosch_msm_66020_pogrugnoy_1.jpg"
}

### endpoint /wishes/last
GET http://127.0.0.1:3000/wishes/last
Authorization: Bearer {{token}}

### endpoint /wishes/top
GET http://127.0.0.1:3000/wishes/top
Authorization: Bearer {{token}}

### endpoint /wishes/{id}
GET http://127.0.0.1:3000/wishes/8
Authorization: Bearer {{token}}

### endpoint /wishes/{id}
PATCH http://127.0.0.1:3000/wishes/8
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Блендер Bosch погружной"
}

### endpoint /wishes/{id}
DELETE http://127.0.0.1:3000/wishes/15
Authorization: Bearer {{token}}

### endpoint /wishes/{id}/copy
POST http://127.0.0.1:3000/wishes/18/copy
Authorization: Bearer {{token}}






### endpoint /offers
POST http://127.0.0.1:3000/offers
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "amount": 100,
    "itemId": 13,
    "hidden": true
}

### endpoint /offers/{id}
GET http://127.0.0.1:3000/offers/1
Authorization: Bearer {{token}}

### endpoint /offers
GET http://127.0.0.1:3000/offers
Authorization: Bearer {{token}}







### endpoint /wishlistlists
POST http://127.0.0.1:3000/wishlistlists
Content-Type: application/json
Authorization: Bearer {{token}}

    # "image": "https://3.bp.blogspot.com/-6DK_0x5JTJo/WEWeFmpCXGI/AAAAAAAAKjk/QdwYT3Y4W80luES2U7Ut6M8AcbDKvMSDQCLcB/s1600/wishlist.jpg",
{
    "name": "Пустой список",
    "itemsId": []
}

### endpoint /wishlistlists
GET http://127.0.0.1:3000/wishlistlists
Authorization: Bearer {{token}}

### endpoint /wishlistlists{id}
GET http://127.0.0.1:3000/wishlistlists/3
Authorization: Bearer {{token}}

### endpoint /wishlistlists{id}
PATCH http://127.0.0.1:3000/wishlistlists/3
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "itemsId": [3, 11]
}

### endpoint /wishlistlists/{id}
DELETE http://127.0.0.1:3000/wishlistlists/5
Authorization: Bearer {{token}}