### Регистрация
POST http://localhost:3000/signup
Content-Type: application/json

{

    "username": "exampleuser5678910111213",
    "about": "exampleuser467891011",
    "avatar": "https://i.pravatar.cc/150?img=3",
    "email": "user5678910111213@yandex.ru",
    "password": "somestrongpassword234"

}

### Авторизация
POST http://127.0.0.1:3000/signin
Content-Type: application/json

{
    "username": "exampleuser5",
    "password": "somestrongpassword234"
}

# {
#     "email": "admin@admin.admin",
#     "password": "admin"
# }

###

# Васёк
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEyLCJpYXQiOjE2NzExMjk2NjMsImV4cCI6MTY3MzcyMTY2M30.qtx2WF7GUeSTw3_yfS2WJh5VdvCW_mAcSY9eRAIbtMI



### endpoint /users/me
GET http://127.0.0.1:3000/users/me
Authorization: Token {{token}}

### endpoint /users/me
GET http://127.0.0.1:3000/users/me/wishes
# Authorization: Token {{token}}

### endpoint /users/me
POST http://127.0.0.1:3000/users
# Authorization: Token {{token}}

