### Регистрация
POST http://localhost:3000/signup
Content-Type: application/json

{

    "username": "exampleuser5678910111213",
    "about": "exampleuser467891011",
    "avatar": "https://i.pravatar.cc/150?img=3",
    "email": "user5678910111213@yandex.ru",
    "password": "somestrongpassword234"

}

### Авторизация
POST http://127.0.0.1:3000/signin
Content-Type: application/json

{
    "username": "exampleuser5",
    "password": "somestrongpassword234"
}

# {
#     "email": "admin@admin.admin",
#     "password": "admin"
# }

###

# Васёк
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEyLCJpYXQiOjE2NzEyMTU5NDUsImV4cCI6MTY3MzgwNzk0NX0.SB0Kx4O-W4BSITZOETfVjLavXP2ODMTK3HZMISR5gNU



### endpoint /users/me
GET http://127.0.0.1:3000/users/me
Authorization: Bearer {{token}}

### endpoint /users/:username
GET http://127.0.0.1:3000/users/exampleuser5
Authorization: Bearer {{token}}

### endpoint /users/find
POST http://127.0.0.1:3000/users/find
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "query": "exampleuser56"
}

### endpoint /users/me
PATCH http://127.0.0.1:3000/users/me
Content-Type: application/json
Authorization: Bearer {{token}}

{

    "username": "exampleuser5",
    "about": "exampleuser5",
    "avatar": "https://i.pravatar.cc/150?img=3",
    "email": "user5@yandex.ru",
    "password": "somestrongpassword234"

}




### endpoint /wishes
POST http://127.0.0.1:3000/wishes
Content-Type: application/json
Authorization: Bearer {{token}}

# {
#     "name": "Колонка JBL PartyBox 110",
#     "link": "https://www.onlinetrade.ru/catalogue/portativnaya_akustika-c311/jbl/kolonka_jbl_partybox_110_jblpartybox110-3373653.html",
#     "price": 40200,
#     "image": "https://static.onlinetrade.ru/img/items/b/kolonka_jbl_partybox_110_2394566_1.jpg"
# }

{
    "name": "Беспроводная микрофонная система JBL Wireless Microphone Set",
    "link": "https://market.yandex.ru/product--besprovodnaia-mikrofonnaia-sistema-jbl-wireless-microphone-set-jblwirelessmic/101824535015?text=%D0%BC%D0%B8%D0%BA%D1%80%D0%BE%D1%84%D0%BE%D0%BD%20jbl&cpc=FIWlcB7TZui_0LM9YakykIucOePHKhLcdndVV2y-8IxwcvSTWUzWcy0kxsLspf3vyLLJC5nzhcnogerUt5mleRVykDeXPu5K6ur2I_bltqwbxtAecOLFYsSOaq5NIoHJtMelLF9E9JRJRDgt3_CdihNqLwcK5za1&sku=101824535015&do-waremd5=9pLuLiWucxyhzu7u61hFpw&cpa=1&nid=26993530",
    "price": 25540,
    "image": "https://avatars.mds.yandex.net/get-marketpic/6014124/pic2fce573f4a660dabb120295b960871cd/orig"
}



